plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'me.micartey'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.toVersion('17')
    targetCompatibility = JavaVersion.toVersion('17')
}

repositories {
    mavenCentral()
    maven {
        name = 'micartey-public'
        url = uri('https://artifacts.micartey.dev/public')
    }
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

    // Viro dependencies
    implementation 'me.micartey:jation:2.4.1'
    implementation 'io.reactivex.rxjava3:rxjava:3.0.11'

    // JavaFX
    implementation 'org.openjfx:javafx-controls:17'
    implementation 'org.openjfx:javafx-fxml:17'

    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc:1.1.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

springBoot {
    mainClass = 'me.micartey.viro.Application'
}

tasks.withType(JavaCompile).configureEach {
    def javafxJmods = System.getenv("JAVAFX_JMODS")
    if (javafxJmods != null && !javafxJmods.isEmpty()) {
        options.compilerArgs += [
                '--module-path', javafxJmods,
                '--add-modules', 'javafx.controls,javafx.fxml'
        ]
    }
}

tasks.withType(Test).configureEach {
    def javafxJmods = System.getenv("JAVAFX_JMODS")
    if (javafxJmods != null && !javafxJmods.isEmpty()) {
        jvmArgs += [
                '--module-path', javafxJmods,
                '--add-modules', 'javafx.controls,javafx.fxml'
        ]
    }
}